# Netlify Configuration File
# This file configures how Netlify builds and deploys your site

[build]
  # The directory where your built files are located
  # For a static HTML site, this is usually the root directory
  publish = "."
  
  # Build command (not needed for static HTML, but here for reference)
  # command = "echo 'No build needed for static HTML!'"

# Redirect rules for clean URLs (optional)
# Uncomment if you want to use clean URLs without .html extension
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache CSS and JS files for 1 year
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images for 1 year
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 404 page configuration
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404
